apiVersion: v1
kind: Secret
metadata:
  name: mongodb
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  connectionString: {{ .Values.mongodbUri | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  jwtSecret: {{ .Values.jwtSecret | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: stripe
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  apiKey: {{ .Values.stripeSecretKey | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: google
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  clientSecret: {{ .Values.googleOauthClientSecret | b64enc | quote }}
  refreshToken: {{ .Values.googleOauthRefreshToken | b64enc | quote }}
