apiVersion: v1
kind: Service
metadata:
  labels:
    app: notifications
    environment: { { .Values.environment } }
  name: notifications
  namespace: { { .Release.Namespace } }
spec:
  ports:
    - name: "http"
      port: { { .Values.ports.notifications } }
      protocol: TCP
      targetPort: { { .Values.ports.notifications } }
  selector:
    app: notifications
  type: ClusterIP
