apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: payments
    environment: {{ .Values.environment }}
  name: payments
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicas.payments }}
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
        environment: {{ .Values.environment }}
    spec:
      containers:
        - image: "{{ .Values.aws.accountId }}.dkr.ecr.{{ .Values.aws.region }}.amazonaws.com/{{ .Values.images.payments }}"
          name: payments
          env:
            - name: PORT
              value: "{{ .Values.ports.payments }}"
            - name: NOTIFICATIONS_HOST
              value: notifications
            - name: NOTIFICATIONS_PORT
              value: "{{ .Values.ports.notifications }}"
            - name: STRIPE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: stripe
                  key: apiKey
          ports:
            - containerPort: {{ .Values.ports.payments }}
              name: http
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
