apiVersion: v1
kind: Service
metadata:
  labels:
    app: payments
    environment: {{ .Values.environment }}
  name: payments
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: "http"
      port: {{ .Values.ports.payments }}
      protocol: TCP
      targetPort: {{ .Values.ports.payments }}
  selector:
    app: payments
  type: ClusterIP
