apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: auth
    environment: { { .Values.environment } }
  name: auth
  namespace: { { .Release.Namespace } }
spec:
  replicas: { { .Values.replicas.auth } }
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
        environment: { { .Values.environment } }
    spec:
      containers:
        - image: "{{ .Values.aws.accountId }}.dkr.ecr.{{ .Values.aws.region }}.amazonaws.com/{{ .Values.images.auth }}"
          name: auth
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: connectionString
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt
                  key: jwtSecret
            - name: JWT_EXPIRATION
              value: "{{ .Values.jwt.expiration }}"
            - name: "TCP_PORT"
              value: "{{ .Values.ports.auth.tcp }}"
            - name: "HTTP_PORT"
              value: "{{ .Values.ports.auth.http }}"
          ports:
            - containerPort: { { .Values.ports.auth.tcp } }
              name: tcp
            - containerPort: { { .Values.ports.auth.http } }
              name: http
          resources:
            requests:
              cpu: { { .Values.resources.requests.cpu } }
              memory: { { .Values.resources.requests.memory } }
            limits:
              cpu: { { .Values.resources.limits.cpu } }
              memory: { { .Values.resources.limits.memory } }
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
