apiVersion: v1
kind: Service
metadata:
  labels:
    app: auth
    environment: {{ .Values.environment }}
  name: auth-tcp
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: "tcp"
      port: {{ .Values.ports.auth.tcp }}
      protocol: TCP
      targetPort: {{ .Values.ports.auth.tcp }}
  selector:
    app: auth
  type: ClusterIP
