apiVersion: v1
kind: Service
metadata:
  labels:
    app: auth
    environment: {{ .Values.environment }}
  name: auth-http
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: "http"
      port: {{ .Values.ports.auth.http }}
      protocol: TCP
      targetPort: {{ .Values.ports.auth.http }}
  selector:
    app: auth
  type: NodePort
